In [1]:
import numpy as np


In [5]:
x = np.random.randint( low = 0, high = 9, size = 10)
print(x)

[4 5 3 6 7 6 0 2 3 0]


In [6]:
x = np.random.rand(3, 3)
print(x)

[[0.07567613 0.53311563 0.12264096]
 [0.58018236 0.9912565  0.88278259]
 [0.42361491 0.45511239 0.59756764]]


In [7]:
x = np.random.rand(3, 3, 3)
print(x)

[[[0.29157613 0.74742222 0.13415983]
  [0.81283952 0.62777595 0.25666381]
  [0.02461932 0.99287139 0.27468036]]

 [[0.99166189 0.64917514 0.20172226]
  [0.75763711 0.02143434 0.13549059]
  [0.48870856 0.11425773 0.30108213]]

 [[0.40094895 0.79026146 0.01840082]
  [0.28471009 0.1755795  0.77017106]
  [0.53915742 0.65507898 0.69303718]]]


In [8]:
x = np.random.rand(2, 2, 2, 2, 2)
print(x)

[[[[[0.56052222 0.61700574]
    [0.14241816 0.85486068]]

   [[0.51484503 0.22730624]
    [0.2016704  0.75107786]]]


  [[[0.97838393 0.29151325]
    [0.53028889 0.76958561]]

   [[0.99236344 0.51505596]
    [0.85270099 0.6446274 ]]]]



 [[[[0.02771634 0.15684486]
    [0.20672917 0.13879172]]

   [[0.25921877 0.03330635]
    [0.59953914 0.50274272]]]


  [[[0.49901232 0.97415366]
    [0.56477939 0.0635811 ]]

   [[0.39700869 0.24416077]
    [0.1862161  0.64470699]]]]]
