In [1]:
import numpy as np

x = np.array([1, 2, 3], np.int16)

In [2]:
print(x)

print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
print(x[0]); print(x[1]); print(x[2])

1
2
3


In [4]:
print(x[-1]); print(x[3])

3


IndexError: index 3 is out of bounds for axis 0 with size 3

In [5]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int16)
print(x)

[[1 2 3]
 [4 5 6]]


In [6]:
print(x[0, 0]); print(x[0, 1]); print(x[0, 2]);

1
2
3


In [8]:
print(x[:, 0])

[1 4]


In [9]:
print(x[:, 1])

[2 5]


In [10]:
print(x[:, 2])

[3 6]


In [11]:
print(x[0, :])

[1 2 3]


In [12]:
print(x[1, :])

[4 5 6]


In [13]:
x = np.array([[[1, 2, 3], [4, 5, 6]],[[0, -1, -2], [-3, -4, -5]]], np.int16)
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 0 -1 -2]
  [-3 -4 -5]]]


In [14]:
print(x [0, 0, 0])

1


In [19]:
print(x [1, 1, 2])

-5


In [23]:
print(x[:, 1, 1])

[ 5 -4]


# NumPy Ndarray Properties

In [24]:
x = np.array([[[1, 2, 3], [4, 5, 6]],[[0, -1, -2], [-3, -4, -5]]], np.int16)
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 0 -1 -2]
  [-3 -4 -5]]]


In [29]:
print(x.shape)
print(x.ndim)
print(x.dtype)

print(x.size)
print(x.nbytes)

(2, 2, 3)
3
int16
12
24


In [30]:
print(x.T)

[[[ 1  0]
  [ 4 -3]]

 [[ 2 -1]
  [ 5 -4]]

 [[ 3 -2]
  [ 6 -5]]]


# NumPy Constants

In [32]:
print(np.inf)
print(np.NAN)
print(np.NINF)
print(np.NZERO)
print(np.PZERO)

print(np.e)
print(np.euler_gamma)
print(np.pi)

inf
nan
-inf
-0.0
0.0
2.718281828459045
0.5772156649015329
3.141592653589793
