# Array Manipulation Routines

In [1]:
import numpy as np
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [2]:
y = x.reshape((3, 2))
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [3]:
x = np.array([[0, 1, 2], [3, 4, 5]], dtype = np.uint8)
print(x)

[[0 1 2]
 [3 4 5]]


In [4]:
y = np.reshape(x, 6)
print(y)

[0 1 2 3 4 5]


In [5]:
print(x)

[[0 1 2]
 [3 4 5]]


In [6]:
y = np.ravel(x)
print(y)

[0 1 2 3 4 5]


In [7]:
print(x)

[[0 1 2]
 [3 4 5]]


In [8]:
y = x.flatten()
print(y)

[0 1 2 3 4 5]


In [9]:
y = x.flatten('C')
print(y)

[0 1 2 3 4 5]


In [10]:
y = x.flatten('F')
print(y)

[0 3 1 4 2 5]


In [11]:
x = np.array([1, 2, 3], dtype = np.uint8)
y = np.array([4, 5, 6], dtype = np.uint8)

print(x.dtype)

print(x)
print(y)

uint8
[1 2 3]
[4 5 6]


In [12]:
z = np.stack((x, y))
print(z)

[[1 2 3]
 [4 5 6]]


In [13]:
z = np.stack((x, y), axis = 0 )
print(z)

[[1 2 3]
 [4 5 6]]


In [14]:
z = np.stack((x, y), axis = -1 )
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [15]:
z = np.stack((x, y), axis = 1 )
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [16]:
print(x)
print(y)

[1 2 3]
[4 5 6]


In [17]:
z = np.dstack((x, y))
print(z)

[[[1 4]
  [2 5]
  [3 6]]]


In [18]:
print(z.shape)

(1, 3, 2)


In [19]:
z = np.hstack((x, y))
print(z)

[1 2 3 4 5 6]


In [20]:
z = np.vstack((x, y))
print(z)

[[1 2 3]
 [4 5 6]]


In [21]:
print(z.shape)

(2, 3)


In [22]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [23]:
a, b, c = np.split(x, 3)
print(a, b, c)

[0 1 2] [3 4 5] [6 7 8]


In [24]:
x = np.random.rand(4, 4, 4)
print(x)

[[[0.82867895 0.55798369 0.49230467 0.21844314]
  [0.8985031  0.42733363 0.32979589 0.70578233]
  [0.91388975 0.67150231 0.32048086 0.47061522]
  [0.45836465 0.52486852 0.53366511 0.47707171]]

 [[0.67350837 0.42134917 0.89965268 0.53596853]
  [0.35375186 0.80671171 0.58357056 0.87714871]
  [0.42000205 0.9189422  0.84925124 0.14562692]
  [0.42360063 0.30240372 0.50437383 0.82756499]]

 [[0.39423342 0.23566706 0.69080503 0.57719095]
  [0.46991132 0.4768163  0.36950844 0.69458716]
  [0.48154213 0.01366563 0.02899281 0.47635254]
  [0.57070943 0.5484706  0.05305312 0.26182953]]

 [[0.40610148 0.63617857 0.61917571 0.83345948]
  [0.67731527 0.66636471 0.90089041 0.06427929]
  [0.90533504 0.18045617 0.67539567 0.74090204]
  [0.67319812 0.76623152 0.37864678 0.9822041 ]]]


In [25]:
y, z = np.split(x, 2)
print(y, z)

[[[0.82867895 0.55798369 0.49230467 0.21844314]
  [0.8985031  0.42733363 0.32979589 0.70578233]
  [0.91388975 0.67150231 0.32048086 0.47061522]
  [0.45836465 0.52486852 0.53366511 0.47707171]]

 [[0.67350837 0.42134917 0.89965268 0.53596853]
  [0.35375186 0.80671171 0.58357056 0.87714871]
  [0.42000205 0.9189422  0.84925124 0.14562692]
  [0.42360063 0.30240372 0.50437383 0.82756499]]] [[[0.39423342 0.23566706 0.69080503 0.57719095]
  [0.46991132 0.4768163  0.36950844 0.69458716]
  [0.48154213 0.01366563 0.02899281 0.47635254]
  [0.57070943 0.5484706  0.05305312 0.26182953]]

 [[0.40610148 0.63617857 0.61917571 0.83345948]
  [0.67731527 0.66636471 0.90089041 0.06427929]
  [0.90533504 0.18045617 0.67539567 0.74090204]
  [0.67319812 0.76623152 0.37864678 0.9822041 ]]]


In [26]:
y, z = np.dsplit(x, 2)
print(y, z)

[[[0.82867895 0.55798369]
  [0.8985031  0.42733363]
  [0.91388975 0.67150231]
  [0.45836465 0.52486852]]

 [[0.67350837 0.42134917]
  [0.35375186 0.80671171]
  [0.42000205 0.9189422 ]
  [0.42360063 0.30240372]]

 [[0.39423342 0.23566706]
  [0.46991132 0.4768163 ]
  [0.48154213 0.01366563]
  [0.57070943 0.5484706 ]]

 [[0.40610148 0.63617857]
  [0.67731527 0.66636471]
  [0.90533504 0.18045617]
  [0.67319812 0.76623152]]] [[[0.49230467 0.21844314]
  [0.32979589 0.70578233]
  [0.32048086 0.47061522]
  [0.53366511 0.47707171]]

 [[0.89965268 0.53596853]
  [0.58357056 0.87714871]
  [0.84925124 0.14562692]
  [0.50437383 0.82756499]]

 [[0.69080503 0.57719095]
  [0.36950844 0.69458716]
  [0.02899281 0.47635254]
  [0.05305312 0.26182953]]

 [[0.61917571 0.83345948]
  [0.90089041 0.06427929]
  [0.67539567 0.74090204]
  [0.37864678 0.9822041 ]]]


In [27]:
y, z = np.hsplit(x, 2)
print(y, z)

[[[0.82867895 0.55798369 0.49230467 0.21844314]
  [0.8985031  0.42733363 0.32979589 0.70578233]]

 [[0.67350837 0.42134917 0.89965268 0.53596853]
  [0.35375186 0.80671171 0.58357056 0.87714871]]

 [[0.39423342 0.23566706 0.69080503 0.57719095]
  [0.46991132 0.4768163  0.36950844 0.69458716]]

 [[0.40610148 0.63617857 0.61917571 0.83345948]
  [0.67731527 0.66636471 0.90089041 0.06427929]]] [[[0.91388975 0.67150231 0.32048086 0.47061522]
  [0.45836465 0.52486852 0.53366511 0.47707171]]

 [[0.42000205 0.9189422  0.84925124 0.14562692]
  [0.42360063 0.30240372 0.50437383 0.82756499]]

 [[0.48154213 0.01366563 0.02899281 0.47635254]
  [0.57070943 0.5484706  0.05305312 0.26182953]]

 [[0.90533504 0.18045617 0.67539567 0.74090204]
  [0.67319812 0.76623152 0.37864678 0.9822041 ]]]


In [28]:
y, z = np.vsplit(x, 2)
print(y, z)

[[[0.82867895 0.55798369 0.49230467 0.21844314]
  [0.8985031  0.42733363 0.32979589 0.70578233]
  [0.91388975 0.67150231 0.32048086 0.47061522]
  [0.45836465 0.52486852 0.53366511 0.47707171]]

 [[0.67350837 0.42134917 0.89965268 0.53596853]
  [0.35375186 0.80671171 0.58357056 0.87714871]
  [0.42000205 0.9189422  0.84925124 0.14562692]
  [0.42360063 0.30240372 0.50437383 0.82756499]]] [[[0.39423342 0.23566706 0.69080503 0.57719095]
  [0.46991132 0.4768163  0.36950844 0.69458716]
  [0.48154213 0.01366563 0.02899281 0.47635254]
  [0.57070943 0.5484706  0.05305312 0.26182953]]

 [[0.40610148 0.63617857 0.61917571 0.83345948]
  [0.67731527 0.66636471 0.90089041 0.06427929]
  [0.90533504 0.18045617 0.67539567 0.74090204]
  [0.67319812 0.76623152 0.37864678 0.9822041 ]]]


In [29]:
x = np.arange(16).reshape(4, 4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [30]:
y = np.flip(x, axis = -1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [31]:
y = np.flip(x, axis = 0)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [32]:
y = np.flip(x, axis = 1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [33]:
y = np.fliplr(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [34]:
y = np.flipud(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [35]:
y = np.roll(x, 8)
print(y)

[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [36]:
y = np.rot90(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]
